[mypy]
python_version = 3.10
warn_unused_ignores = True
no_implicit_optional = True
warn_return_any = True
disallow_untyped_defs = True
check_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
warn_no_return = True
strict_equality = True
warn_redundant_casts = True
warn_unreachable = True
no_implicit_reexport = True
disallow_any_generics = True


[mypy-mautrix.*]
ignore_missing_imports = True

[mypy-maubot.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-csreg_scanner.db]
warn_unreachable = False
